version: '3.1'
services:

    mysql_db:
        container_name: ${MYSQL_CONTAINER_NAME}
        image: ${MYSQL_IMAGE}
        command: ${MYSQL_COMMAND}
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_PORT}
        expose:
            - ${MYSQL_EXPOSE}
        volumes:
            - ${MYSQL_VOLUME}
    
    mongo_db:
        container_name: ${MONGO_CONTAINER_NAME}
        image: ${MONGO_IMAGE}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - ${MONGO_PORT}
        expose:
            - ${MONGO_EXPOSE}
        
        
        